version: '3'

networks:
  greedie_network:
    driver: bridge
    external: true

services:
  mysql:
    image: mysql
    networks:
      - greedie_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-init.d
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
  banking-service:
    restart: on-failure
    image: greedie-pay-banking-service:0.0.0
    networks:
      - greedie_network
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
