version: '3'
services:
  mysql:
    image: mysql
    networks:
      - jaypay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-init.d
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
  banking-service:
    image: greedie-pay-banking-service:0.0.0
    networks:
      - jaypay_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jay_pay
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
networks:
  jaypay_network:
    driver: bridge